# Generated by Django 2.1.2 on 2019-02-12 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='cost',
        ),
    ]
